require 'keymaps'
require 'plugins'
require 'settings'
require 'plugins.configs.compe'
require 'lsp'
require 'plugins.configs.statusline'
require 'plugins.configs.toggleterm'
require 'plugins.configs.formatter'
